### ISSUE TITLE
MeteoInfoMap.jar   maskout  能否指定shp文件中某一个图元

### ISSUE THREAD

**Issue by boyucjz** [meteoinfo/MeteoInfo#11]
MeteoInfoMap.jar   maskout  能否指定shp文件中某一个图元
基于MeteoInfoMap.jar 做二次开发，生成色斑图，需要让用户选择生成的区划。

**Comment by Yaqiang** [comment]
You can refer to this code: https://github.com/meteoinfo/MeteoInfo/blob/37f3695b6816ae12fb126dc43f2e1d44f14486ff/MeteoInfoLib/src/main/java/org/meteoinfo/map/MapView.java#L6057

**Comment by boyucjz** [comment]
谢谢
