### ISSUE TITLE
MeteoInfoLab中颜色透明度无法设置

### ISSUE THREAD

**Issue by gqians** [meteoinfo/MeteoInfo#12]
![2021-03-10 11-17-50 的屏幕截图](https://user-images.githubusercontent.com/38391044/110571291-4e12df00-8192-11eb-9e38-81738c1593c4.png)

![2021-03-10 11-15-16 的屏幕截图](https://user-images.githubusercontent.com/38391044/110571062-f07e9280-8191-11eb-89fa-c191f5aaac14.png)
期待解决方案。

**Comment by Yaqiang** [comment]
just try

`>>> cols[0].getAlpha()`

**Comment by gqians** [comment]
确实可以取到透明度，但是将多个带有透明度的颜色添加到 contourfm() 函数的colors参数后，透明度不会生效。如果只是添加一个带有透明度的颜色时，透明度才会生效。

**Comment by Yaqiang** [comment]
没发现你说的问题：
![colors_alpha](https://user-images.githubusercontent.com/4408029/110757704-a6c3a400-8286-11eb-98a8-6c4da1f3f6a1.png)

**Comment by gqians** [comment]
看了您的脚本之后，我发现是我的颜色个数和等级个数不匹配导致的异常现象。我的颜色比我的等级多了三个，在我删除了两个之后脚本就正常了，非常感谢您的回复！
