### ISSUE TITLE
Issue using convert2nc

### ISSUE THREAD

**Issue by ssori1508** [meteoinfo/MeteoInfo#14]
Hi,

I'm trying to convert ARL data file to NC file using covert2nc function. 

Here's the error I'm getting on python. Could you please help me solve this issue?

![image](https://user-images.githubusercontent.com/42046911/124430320-e0cc2080-dd23-11eb-9b28-b402ac6db633.png)

**Comment by Yaqiang** [comment]
Please find this commit: https://github.com/meteoinfo/MeteoInfo/commit/46ace6fc7a333b6edca964b35ef995d3f3a66a6d.

**Comment by Yaqiang** [comment]
This issue has been revised in version 3.0.4: http://www.meteothink.org/downloads/index.html.
