### ISSUE TITLE
请问meteoinfolab有mac版本吗？

### ISSUE THREAD

**Issue by chung9916** [meteoinfo/MeteoInfo#22]
作者您好，我有几个问题想要请教一下：
请问meteoinfolab有mac版本吗？哪里下载呢？
网站上的代码能放到python里面运行吗？

**Comment by Yaqiang** [comment]
MeteoInfoLab can run in mac or any other computers with Java 8 or higher version pre-installed. Please look at the online information: http://www.meteothink.org/docs/introduction.html#running-meteoinfomap-meteoinfolab.

The online example code can not run in CPython environment.
