### ISSUE TITLE
can't open the MeteoInfo_3.3.0

### ISSUE THREAD

**Issue by MoonLightSAMA** [meteoinfo/MeteoInfo#24]
Dr. Wang:
recently, I want to upgrade the MeteoInfo from V3.0.1 to V3.3.0.
but, I can't open the  MeteoInfoLab.exe, and receive application error.
Below is the error message:
![image](https://user-images.githubusercontent.com/45427024/183593790-88204d0a-d359-4f22-8b25-c9e0e8fc9efc.png)
When I try to open the MeteoInfoMap.exe, the loading screen flashed by and main screen will not appear later.
These things only happen in V3.3.0.
I can normal use V3.0.1 without any error on the same computer.
I don't know why this is happening~

**Comment by Yaqiang** [comment]
64 bit Java version is needed to run MeteoInfo. Java 11 64 bit version is suggested.

**Comment by MoonLightSAMA** [comment]
> 64 bit Java version is needed to run MeteoInfo. Java 11 64 bit version is suggested.

Thanks, the problem has been solved. 
I found that Java 8 32bit was downloaded by default if I choose the online package at [this webpage](https://www.java.com/zh-CN/download/manual.jsp). 
Finally, I chose the Java 8 64bit, while the Oracle Account is requested when I try to download the Java 11.
