### ISSUE TITLE
报 found non-noded intersection between LINESTRING 异常

### ISSUE THREAD

**Issue by xcmonline** [meteoinfo/MeteoInfo#27]
如果再增加一个小的色阶值及颜色[3,5,7,9,11,13,15,17] [Color.pink,Color.cyan,Color.white,Color.blue,Color.green,Color.yellow,Color.red,Color.orange,Color.gray]还是会报 found non-noded intersection between LINESTRING 异常。

**Comment by Yaqiang** [comment]
This issue is introduced by contour smoothing process which may result in the linestrings of the contour polygon self-intersection. So the possible solution is to skip contour line smoothing process through setting the las argument to false in the following code line.
```
VectorLayer layer = DrawMeteoData.createShadedLayer(grid, aLS, "Shaded_var", "var", false);
```

**Comment by xcmonline** [comment]
谢谢！
