### ISSUE TITLE
绘制Barb图，显示为圆点。

### ISSUE THREAD

**Issue by xcmonline** [meteoinfo/MeteoInfo#28]
![image](https://user-images.githubusercontent.com/20119396/196907223-648d3c5e-a99d-4add-8c75-ed9a77b7423f.png)

                    //风杆
                    layer = DrawMeteoData.createGridBarbLayer(
                            grid.getData(),
                            grid.getData2(),
                            grid.getData2(),
                            als,
                            true,
                            "Barb_var",
                            false
                    );

                    layer = layer.clip(clipShp);

还是一样执行 clip 剪裁就会没有风杆，只显示圆点。

MeteoInfo-3.4
os windows 10

**Comment by Yaqiang** [comment]
Try following code:

layer.setLayerDrawType(LayerDrawType.VECTOR);

**Comment by Yaqiang** [comment]
The bug was solved by this commit: https://github.com/meteoinfo/MeteoInfo/commit/fa4fd665328d5ae9946a26a891f77f0b20b89971.

**Comment by xcmonline** [comment]
谢谢！
