### ISSUE TITLE
Running MeteoInfo on Mac

### ISSUE THREAD

**Issue by DamienIrving** [meteoinfo/MeteoInfo#3]
I downloaded MeteoInfo from the following link:
http://www.meteothink.org/downloads/files/MeteoInfo_1.7.5.zip

I'm on a mac, so the README says the following:
```
you should run MeteoInfo from the shell command line; 'cd' into
  the directory where the above files are located and then type:
  
  ./meteoinfo.sh
```

That `meteoinfo.sh` file doesn't appear to exist in the zip file that I downloaded?

**Comment by Yaqiang** [comment]
The README.txt is quite old and I forgot to update it. Please refer to the document on MeteoInfo website: http://www.meteothink.org/docs/introduction.html#running-meteoinfomap-meteoinfolab .
