### ISSUE TITLE
#26问题在centos环境中使用clip按行政裁剪异常Points of LinearRing do not form a closed linestring

### ISSUE THREAD

**Issue by xcmonline** [meteoinfo/MeteoInfo#30]
在#26异常修复后在window下运行没有问题，但在Centos8中运行一批文件生成色班图基本有40%左右异常提示Points of LinearRing do not form a closed linestring，多次运行，异常的文件都有不同。但这些文件复制到windows环境下生成色斑图正常（配置一致）。

**Comment by Yaqiang** [comment]
Unfortunatelly, I have no computer with Centos8 to reproduce and debug this issue.
