### ISSUE TITLE
[MeteoInfoLab] Unable to read data after loading OPeNDAP remote file

### ISSUE THREAD

**Issue by 66grand** [meteoinfo/MeteoInfo#31]
# Describe
As the title.

# How To Reproduce
code
~~~
f = addfile('http://nomads.ncep.noaa.gov:80/dods/gfs_0p25_1hr/gfs20230320/gfs_0p25_1hr_00z')
v = f['hpblsfc']
ps = v[0,:,:]
~~~
output:
~~~
Traceback (most recent call last):
  File "<iostream>", line 4, in <module>
  File "C:\Users\xxxx\AppData\Local\Programs\Portable\MeteoInfo\pylib\mipylib\dataset\dimvariable.py", line 296, in __getitem__
    if rr.getSize() == 1:
AttributeError: 'NoneType' object has no attribute 'getSize'
~~~

# Environment
- OS: windows11
- Version: MeteoInfoLab 3.5.9

**Comment by Yaqiang** [comment]
Thanks for your bug report! It has been solved by this PR: https://github.com/meteoinfo/MeteoInfo/commit/5aba94c0dd94e1a942af458c457eb591c91ce3f5. You can build MeteoInfo yourself or waiting for new released version.

**Comment by Yaqiang** [comment]
A new version of MeteoInfo 3.5.10 was issued.

**Comment by 66grand** [comment]
Thanks for the fix.
