### ISSUE TITLE
关于  MeteoInfo/meteoinfo-data/src/main/java/org/meteoinfo/data/GridData.java

### ISSUE THREAD

**Issue by yzh549345916** [meteoinfo/MeteoInfo#32]
请问为什么要注释掉“if (this.getYDelta() < 0)”这段代码，注释以后会导致读取经纬度倒序的格点数据没办法正常读取。

**Comment by Yaqiang** [comment]
We try to keep the original data structure, but to solve the inverse order problem in plotting functions, such as 'createContourLayer' function in https://github.com/meteoinfo/MeteoInfo/blob/master/meteoinfo-geo/src/main/java/org/meteoinfo/geo/meteodata/DrawMeteoData.java.
