### ISSUE TITLE
如何获得或计算LayoutLegend高度

### ISSUE THREAD

**Issue by hioak** [meteoinfo/MeteoInfo#35]
在调用meteoinfo类库生成色斑图经常会碰到这种情况：图例放到色斑图的右下角。但是图例的高度如果不确定，就不能准确的放到指定的位置。在程序中图例是动态的LegendBreak的数量是动态的，所以不好设置固定高度。
目前类库中是否存在获取LayoutLegend高度的方法或者设置LayoutLegend bottom和right属性，让图例靠右下角对齐。

**Comment by Yaqiang** [comment]
Using getHeight function of LayoutLegend.
