### ISSUE TITLE
VectoryLayer addLabels方法labels被遮照图层遮挡

### ISSUE THREAD

**Issue by hioak** [meteoinfo/MeteoInfo#36]
map layer 使用 mask layer 遮照。在map layer上添加label。在map layer边沿label显示不全。有办法解决吗？
<img width="574" alt="图片" src="https://github.com/meteoinfo/MeteoInfo/assets/3831083/b69fd0b7-4b49-450b-8d32-3ece9affa973">

**Comment by Yaqiang** [comment]
You can set each layer maskout or not using "setMaskout" method of the MapLayer. In this case, the station point layer can use setMaskout(false) to avoid label masked.

**Comment by hioak** [comment]
谢谢老师指点！但现在有个问题，有些站点在行政区划外，要去除这些站点，在不使用mask layout的情况下，如何实现？有工具类可以用吗？

**Comment by Yaqiang** [comment]
Please refer here: https://github.com/meteoinfo/MeteoInfo/blob/master/meteoinfo-geometry/src/main/java/org/meteoinfo/geometry/geoprocess/GeometryUtil.java#L553.

**Comment by hioak** [comment]
好的，我试试。谢谢老师。
