### ISSUE TITLE
MeteoInfo-3.7.0 严重bug反馈

### ISSUE THREAD

**Issue by HPLoveGLL** [meteoinfo/MeteoInfo#37]
1、读取S2S-CMA资料时，GirdData对象中的纬度集合顺序错了，结果是从大到小顺序，导致获取最小纬度和最大纬度出错，最终导致网格插值到站点时，全部为NaN，导致失败。
2、EC，S2S模式资料都是多成员预报网格，目前各个版本只能读取单个成员变量的预报网格，不知是否可以升级，支持多成员的网格读取。
感谢

**Comment by Yaqiang** [comment]
Please provide the sameple data file and code so I can re-produce the issue on my side.

**Comment by HPLoveGLL** [comment]
[s2s_babj_2023_20230911_2t.zip](https://github.com/meteoinfo/MeteoInfo/files/12685437/s2s_babj_2023_20230911_2t.zip)

**Comment by Yaqiang** [comment]
Four ensemble members could be read from the data file.
![s2s_babj](https://github.com/meteoinfo/MeteoInfo/assets/4408029/491976a2-356c-42f6-9362-48d4fbf71ac7)

**Comment by HPLoveGLL** [comment]
不好意思，是我没有说清楚，不是Python脚本的问题，是 org.meteoinfo.data.GridData中的问题，以及MeteoDataInfo 读取多成员的问题

` @Test
    public void 解析S2S() {
        String filePath = "D:\\ZSD\\S2S\\EC\\s2s_ecmf_2023_20230911_2t.grib";

        MeteoDataInfo dataInfo = new MeteoDataInfo();
        dataInfo.openNetCDFData(filePath);

        List<Variable> variables = dataInfo.getDataInfo().getVariables();
        AtomicReference<String> gridVarName = new AtomicReference<>("");
        variables.forEach(var -> {
            System.out.println(String.format("变量名称：%s,是否可以读取格点数据：%s", var.getName(), var.isPlottable()));
            if (var.isPlottable()) {
                gridVarName.set(var.getName());
            }
        });

        Variable variable = dataInfo.getDataInfo().getVariable(gridVarName.get());
        List<LocalDateTime> times = variable.getTimes();
        List<String> dates = new ArrayList<>();
        times.forEach(time -> dates.add(time.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"))));
        System.out.println("所有日期=============================");
        System.out.println(dates);
        List<Double> ens = dataInfo.getDataInfo().getVariable("ens").getDimensions().get(0).getDimValueList();
        System.out.println("成员数============================= " + ens.size());

        List<DailyGrid> dailyGrids = new ArrayList<>();
        List<JSONObject> stationValues = new ArrayList<>();
        IntStream.range(0, dates.size()).forEach(i -> {
            dataInfo.setTimeIndex(i);
            GridData gridData = dataInfo.getGridData(gridVarName.get());//这里只能获取到第一个成员的网格数据，无法获取其他成员的网格数据
            dailyGrids.add(new DailyGrid(new DateTime(dates.get(i)), gridData));

        //gridData.toStation_Gaussian(117.9, 32.9333) 这句话无法实现网格插值到站点，因为gridData对象中的yArray值顺序是错的，期望顺序是从小到大，实际是从大到小，导致获取其最小值和最大值是错误的，最终导致   if (!(x < xmin) && !(x > xmax) && !(y < ymin) && !(y > ymax)) 判断条件不通过
            stationValues.add(new JSONObject().fluentPut("date", dates.get(i)).fluentPut("dataValue", gridData.toStation_Gaussian(117.9, 32.9333)));
        });
        System.out.println(String.format(" ============================= 数据量大小：%s", dailyGrids.size()));
        System.out.println(JSONObject.toJSONString(stationValues));


        dataInfo.close();
    }`

**Comment by Yaqiang** [comment]
对于GridData的读取只适合变量维是时间、高度、纬度、经度的情况。集合预报就不适合了。

**Comment by HPLoveGLL** [comment]
> 对于GridData的读取只适合变量维是时间、高度、纬度、经度的情况。集合预报就不适合了。

OK,明白了，那插值站点的如何解决呢，有办法吗，感谢您的回复

**Comment by Yaqiang** [comment]
没看明白你的问题

**Comment by Yaqiang** [comment]
你可以考虑加入MeteoInfo QQ群（361327727），方面交流
