### ISSUE TITLE
关于读取多层次多要素多时次的grib文件问题

### ISSUE THREAD

**Issue by XiaoPenPen** [meteoinfo/MeteoInfo#4]
您好，我这边也是使用的netcdf5.1 但是读取的单要素单层次多时次的文件 数据没有问题，但是接下来的多层次文件 对其中的数据结构翻阅了很多资料也没有找到解答，能请教下如何解析这种类型文件吗

**Comment by Yaqiang** [comment]
netcdf库对不同数据格式最终用了统一的数据结构，grib使用起来和其它格式数据没什么区别。

**Comment by XiaoPenPen** [comment]
非常感谢您能回复我的问题，在org.meteoinfo.data.meteodata.grib.grib2.GRIB2DataInfo中没有找到相应的解析方法
![image](https://user-images.githubusercontent.com/42669253/65745888-c8cb7400-e12f-11e9-900c-3dfe341883a7.png)目前是这样读取grib2格式文件，读取出的数据 和 部分信息可以MeteoInfo读取出来的相匹配，但是如果多个数据要素多个层次在一起的，我目前弄不清楚它们的排列方式，并且在您的源码没有找到读取grib文件的位置，十分期望您的回答 谢谢！

**Comment by Yaqiang** [comment]
没有做单独的grib数据读取模块，都在NetCDFDataInfo里。

**Comment by XiaoPenPen** [comment]
十分感谢您的回答，我再去研究研究吧 谢谢！

**Comment by Anyuei** [comment]
[INFO] MeteoInfo .......................................... SUCCESS [  0.695 s]
[INFO] MeteoInfoLib ....................................... FAILURE [  0.326 s]
[INFO] MeteoInfoMap ....................................... SKIPPED
[INFO] MeteoInfoLab ....................................... SKIPPED
项目导入eclipse建立maven失败，开始是安全证书问题，现在是找不到依赖
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project MeteoInfoLib: Could not resolve dependencies for project org.meteothink:MeteoInfoLib:jar:1.9: Failed to collect dependencies at org.meteothink:jts-core:jar:1.15.1

**Comment by XiaoPenPen** [comment]
> [INFO] MeteoInfo .......................................... SUCCESS [ 0.695 s]
> [INFO] MeteoInfoLib ....................................... FAILURE [ 0.326 s]
> [INFO] MeteoInfoMap ....................................... SKIPPED
> [INFO] MeteoInfoLab ....................................... SKIPPED
> 项目导入eclipse建立maven失败，开始是安全证书问题，现在是找不到依赖
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project MeteoInfoLib: Could not resolve dependencies for project org.meteothink:MeteoInfoLib:jar:1.9: Failed to collect dependencies at org.meteothink:jts-core:jar:1.15.1
我的程序也没有运行起来

**Comment by Anyuei** [comment]
不太会搞maven，得找个maven大佬来给我install一下。还是环境有问题

> 
> 
> > [INFO] MeteoInfo .......................................... SUCCESS [ 0.695 s]
> > [INFO] MeteoInfoLib ....................................... FAILURE [ 0.326 s]
> > [INFO] MeteoInfoMap ....................................... SKIPPED
> > [INFO] MeteoInfoLab ....................................... SKIPPED
> > 项目导入eclipse建立maven失败，开始是安全证书问题，现在是找不到依赖
> > org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project MeteoInfoLib: Could not resolve dependencies for project org.meteothink:MeteoInfoLib:jar:1.9: Failed to collect dependencies at org.meteothink:jts-core:jar:1.15.1
> > 我的程序也没有运行起来

不太会搞maven，得找个maven大佬来给我install一下。还是环境有问题

**Comment by Anyuei** [comment]
<dependency>
            <groupId>org.meteothink</groupId>
            <artifactId>jts-core</artifactId>
            <version>1.15.1</version>
        </dependency>
这个依赖一直是解决不了
