### ISSUE TITLE
MICAPS的diamond131类产品类型识别错误

### ISSUE THREAD

**Issue by hqb72** [meteoinfo/MeteoInfo#43]
## 方法openMICAPSData会将diamond131类产品识别为diamond1类产品,导致解析失败
- ![image](https://github.com/user-attachments/assets/a17d2c02-d3d3-4d0d-89aa-4e40eef35a34)
- 版本:
   - ![image](https://github.com/user-attachments/assets/851bee4d-2364-4159-af84-85bf3bb5cfe0)
## 源码大致位置,MICAPSDataInfo.java:71
- ![image](https://github.com/user-attachments/assets/7eb0fc22-4be8-4a16-85a6-5e94657aaf3c)
## 临时解决方案
- 通过openData能正常识别, 这边另一套识别代码(无奈~)

**Comment by Yaqiang** [comment]
Can you please to provide an example data file for testing purpose?

**Comment by hqb72** [comment]
> Can you please to provide an example data file for testing purpose?

[131.zip](https://github.com/user-attachments/files/17640510/131.zip)

解压后就是测试文件了

**Comment by Yaqiang** [comment]
The bug has been fixed with this commit: https://github.com/meteoinfo/MeteoInfo/commit/be48f3c9cce18106f2703ff6f3fa8ff50e7b6c2f

**Comment by hqb72** [comment]
好的
