### ISSUE TITLE
MapLayout新增多个MapFrame后导出图片只显示主MapFrame中的内容

### ISSUE THREAD

**Issue by xcmonline** [meteoinfo/MeteoInfo#44]
VectorLayer shadedLayer = DrawMeteoData.createShadedLayer(gridData,legendScheme,"tem","tem",true);

MapView mapView = new MapView();
mapView.addLayer(shadedLayer );

MapView mapSubView = new MapView();
mapSubView.addLayer(shadedLayer );

MapLayout mapLayout = new MapLayout();
mapLayout.setPageBounds(new Rectangle(0,0,420,420));

MapFrame mapFrame = mapLayout.getActiveMapFrame();
mapFrame.setLayoutBounds(new Rectangle(0, 0, 200, 200));
mapFrame.setMapFrameName("main");
mapFrame.setMapView(mapView);

MapFrame subFrame = new MapFrame();
subFrame.setLayoutBounds(new Rectangle(210, 0, 200, 200));
subFrame.setMapFrameName("sub");
subFrame.setMapView(mapSubView);
mapLayout.getMapFrames().add(0,subFrame);

mapLayout.exportToPicture("d:/data/test.png");

二个MapFrame位置的位置是并列，导出图片，图片中只能显示第一个(mapFrame)内容，第二个位置处空白(subFrame)。

**Comment by Yaqiang** [comment]
I am very busy in these days. Cloud you please debug and try to find the issue from MeteoInfo source code?

**Comment by xcmonline** [comment]
使用 exportToPicture导出是判断  _layoutElements  的列表要素。
Iterator var2 = this._layoutElements.iterator(); 
而增加MapFrame只增加_mapFrames的列表，并没有相应的在 _layoutElements 中增加要素。
需要手动增加_layoutElements列表。
LayoutMap layoutMap = new LayoutMap(subFrame, null);
mapLayout.addElement(layoutMap);
