### ISSUE TITLE
Maven搭建失败，缺少依赖

### ISSUE THREAD

**Issue by Anyuei** [meteoinfo/MeteoInfo#5]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project MeteoInfoLib: Could not resolve dependencies for project org.meteothink:MeteoInfoLib:jar:1.9: Failed to collect dependencies at org.meteothink:jts-core:jar:1.15.1

**Comment by Anyuei** [comment]
不太会搞maven，得找个maven大佬来给我install一下。还是环境有问题

**Comment by Yaqiang** [comment]
也可以在这里下载缺失的 jts 库（https://search.maven.org/search?q=a:jts-core），然后安装到本机Maven库中，如何安装请自行上网搜索。

**Comment by Anyuei** [comment]
恩恩 谢谢前辈！
