### ISSUE TITLE
Views.java 类中出现List<String>，List<Object>类型不匹配错误

### ISSUE THREAD

**Issue by Anyuei** [meteoinfo/MeteoInfo#7]
MeteoInfo-master\MeteoInfoLib\src\main\java\org\meteoinfo\data\dataframe\impl\Views.java 类中
entrySet中的迭代器iterator类型不匹配。
尝试用以下方法解决：
添加转换方法：
`        public static <T> List<T> castList(Object obj, Class<T> clazz)
        {
            List<T> result = new ArrayList<T>();
            if(obj instanceof List<?>)
            {
                for (Object o : (List<?>) obj)
                {
                    result.add(clazz.cast(o));
                }
                return result;
            }
            return null;
        }`
使用转换方法：
final List<Object> names = transpose ? df.getIndex().getValues() : castList(df.getColumns().getNames(), Object.class);

**Comment by Yaqiang** [comment]
Change to:

final List<Object> names = transpose ? df.getIndex().getValues() : new ArrayList<>(df.getColumns().getNames());

**Comment by Anyuei** [comment]
That's OK
