### ISSUE TITLE
AWX to PNG

### ISSUE THREAD

**Issue by jovi521** [meteoinfo/MeteoInfo#8]
I want to change a .awx file to .png. But I don't konw how to paser it. Please help me, provide an idea.

**Comment by Yaqiang** [comment]
Read 2d data array from the .awx file, plot the data, save the plot to .png file.

Following is an example script:

`fn = 'D:/Temp/FY/FY2D_TBB_IR1_OTG_20080630_1315.AWX'
f = addfile_awx(fn)
data = f['var'][:,:]
#Plot
axesm()
geoshow('country', edgecolor='k')
geoshow('cn_province', edgecolor='k')
layer = imshowm(data, 20)
colorbar(layer, label='K')
title('TBB - AWX')
#Save png file
savefig('D:/Temp/test/fy2d_tbb.png', width=600, height=700, dpi=150)`

**Comment by jovi521** [comment]
![image](https://user-images.githubusercontent.com/25958206/88125081-1a824500-cc01-11ea-9f92-9d447797134e.png)
![image](https://user-images.githubusercontent.com/25958206/88125178-48678980-cc01-11ea-8031-03b71feb85c1.png)
`def geoshow(*args, **kwargs):
    '''
    Display map layer or longitude latitude data.
    
    Syntax:
    --------    
        geoshow(shapefilename) - Displays the map data from a shape file.
        geoshow(layer) - Displays the map data from a map layer which may created by ``shaperead`` function.
        geoshow(S) - Displays the vector geographic features stored in S as points, multipoints, lines, or 
          polygons.
        geoshow(lat, lon) - Displays the latitude and longitude vectors.
    '''
    global gca
    if g_figure is None:
        figure()
        
    if gca is None:    
        gca = axesm()
    else:
        if gca.axestype != 'map':
            gca = axesm()
            
    r = gca.geoshow(*args, **kwargs)
    if not r is None:
        draw_if_interactive()
    
    return r`
> `def imshowm(*args, **kwargs):
global gca
    if g_figure is None:
        figure()
        
    if gca is None:    
        gca = axesm()
    else:
        if gca.axestype != 'map':
            gca = axesm()
            
    r = gca.imshow(*args, **kwargs)
    if not r is None:
        draw_if_interactive()
    
    return r`
`def title(label, loc='center', fontname=None, fontsize=14, bold=True, color='black', **kwargs):
    """
    Set a title of the current axes.
    
    :param label: (*string*) Title label string.
    :param loc: (*string') Which title to set ['center' | 'left' | 'right'],
        default to 'center'.
    :param fontname: (*string*) Font name. Default is ``None``, using ``Arial`` .
    :param fontsize: (*int*) Font size. Default is ``14`` .
    :param bold: (*boolean*) Is bold font or not. Default is ``True`` .
    :param color: (*color*) Title string color. Default is ``black`` .  
    :param linespace: (*int*) Line space of multiple line title.
    """
    r = gca.set_title(label, loc, fontname, fontsize, bold, color, **kwargs)
    draw_if_interactive()
    return r`
![image](https://user-images.githubusercontent.com/25958206/88125593-2e7a7680-cc02-11ea-9fb2-fa56f30c5920.png)

**Comment by jovi521** [comment]
Python?......I'm a javaer.I don't konw how to use it.So I still don't konw how to parse AWX to PNG

**Comment by Yaqiang** [comment]
I suggest you to learn Jython to understand the code.

**Comment by jovi521** [comment]
OK. I have read you some code. And I saw you parsed it successfully,such as:
![image](https://user-images.githubusercontent.com/25958206/88138112-a1461a80-cc1f-11ea-8248-1882e7f7b039.png)
Is it right?But, AWX file is belongs to SAT96 or SAT2004. Their standard like this:
![image](https://user-images.githubusercontent.com/25958206/88138405-30533280-cc20-11ea-9688-45f890f6cef7.png)
You just had the data:
![image](https://user-images.githubusercontent.com/25958206/88138474-4eb92e00-cc20-11ea-8452-dd0a65282c69.png)
No NO1-File-Head and NO2-File-Head. Is it right or haven't achieve it?

**Comment by Yaqiang** [comment]
Please find the awx file decoding code here: https://github.com/meteoinfo/MeteoInfo/blob/master/MeteoInfoLib/src/main/java/org/meteoinfo/data/meteodata/awx/AWXDataInfo.java
