### ISSUE TITLE
Many methods are out time

### ISSUE THREAD

**Issue by jovi521** [meteoinfo/MeteoInfo#9]
![image](https://user-images.githubusercontent.com/25958206/88124719-5668da80-cc00-11ea-95a8-cb51bf0c56e8.png)
org.meteoinfo.data.meteodata.netcdf.NetCDFDataInfo
org.meteoinfo.data.meteodata.netcdf.NCUtil

**Comment by Yaqiang** [comment]
I know this situation that NetCDF Java library is changing a lot of the API. The new APIs are still in testing status, so I prefer to keep old API at present. The APIs usage will be updated after the new APIs of NetCDF library are stable.

**Comment by jovi521** [comment]
I got it, thanks
